spring:
  redis:
    host: 填自己的
    port: 6379
    password: 填自己的
  application:
    name: gateway
  cloud:
      gateway:
        globalcors:
          cors-configurations:
            '[/**]':
              allowCredentials: true
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
        routes:
          - id: ucenter
            uri: http://localhost:8001/
            predicates:
            - Path=/api/ucenter/**
            filters:
            - StripPrefix=1
          - id: baidu
            uri: https://www.baidu.com/
            predicates:
            - Path=/

server:
  port: 8000

config:
  jwt:
    secret: bduadedaeded
    expire: 3600
    header: token

