spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sso?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ucenter
  redis:
    host: 112.74.180.80
    port: 6379
    password: 填自己的

server:
  port: 8001
mybatis-plus:
  mapper-locations: classpath:com/gyg/user/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.gyg: debug

